.\* pigLatin man page for CSCI241
.\" Nuriel Leve and Esme Rubinstein - Fall 2020

.TH pigLatin 1 "29 October 2020" "CSCI 241" "Oberlin College"

.SH NAME
.B pigLatin
\- translates a word from English to pig latin

.SH SYNOPSIS
.B pigLatin
[OPTION] <string>

.SH DESCRIPTION
It reads in a string, and translates it from its standard English word into pig latin

.SH OPTIONS
.IP "-h, -?"
Prints out a message on how to use pigLatin and exits the program

.SH AUTHOR
Nuriel Leve and Esme Rubinstein (Fall 2020)

.SH BUGS
None!
