.\" unpigLatin man page for CSCI 241 
.\" Nuriel Leve & Esme Rubinstein  - Fall 2020

.TH unpigLatin 1 "29 October 2020" "CSCI 241" "Oberlin College"

.SH NAME
.B unpigLatin
\- translates a word from pig latin into English

.SH SYNOPSIS
.B unpigLatin
[OPTION] <string>

.SH DESCRIPTION
It reads in a string that is in pig latin and converts it into English

.SH OPTIONS
.IP "-h, -?"
Prints out a message on how to use unpigLatin and exits the program

.SH AUTHOR
Nuriel Leve and Esme Rubinstein (Fall 2020)

.SH BUGS
None!
